language: node_js
node_js: stable

install:
    - npm install -g gulp
    - npm install

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    - npm test
    - if [[ "$TRAVIS_TAG" ]]; then gulp release --env=production; fi

cache:
    directories:
    - node_modules

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "releases/notes_amd64.deb"
  skip_cleanup: true
  on:
    tags: true